name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v7

      - id: beam
        uses: erlef/setup-beam@v1
        with:
          version-type: strict
          version-file: .tool-versions

      - name: Restore deps and build cache
        uses: actions/cache@v6
        with:
          path: |
            deps
            _build
          key: test-${{ steps.beam.outputs.elixir-version }}-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            test-${{ steps.beam.outputs.elixir-version }}-${{ github.head_ref || github.ref }}-
            test-${{ steps.beam.outputs.elixir-version }}-refs/heads/master-

      - run: mix deps.get --only $MIX_ENV
      - run: mix deps.get --check-locked
      - run: mix deps.unlock --check-unused
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted

      - run: docker run -d -p 9000:9000 minio/minio server /data

      - run: mix test --include minio
        env:
          MINIO_REGION: us-east-1
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
          MINIO_ENDPOINT_URL: http://127.0.0.1:9000

      - name: Restore PLTs cache
        uses: actions/cache@v6
        with:
          path: plts
          key: plts-${{ steps.beam.outputs.elixir-version }}-${{ github.head_ref || github.ref }}
          restore-keys: |
            plts-${{ steps.beam.outputs.elixir-version }}-refs/heads/master

      - run: mix dialyzer --format github
